name: senta
description: A new Flutter application.

# TODO: Update packages to the latest version. Then you migrate it to androidX.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: any
  firebase_auth: ^0.7.0
  page_transition: ^1.1.0
  circular_bottom_navigation: ^1.0.0
  cloud_firestore: ^0.8.2+3
  image_picker: ^0.4.12+1
  firebase_storage: ^1.0.4
  random_string: ^0.0.2
  #flushbar: ^1.5.0
  flushbar:
    git:
      url: https://github.com/AndreHaueisen/flushbar
      ref: dev_version
  http: ^0.12.0+2

  # These are already Migrated to AndroidX:
  file_picker: ^1.3.5
  path: ^1.6.2

  cupertino_icons: ^0.1.2

flutter_icons:
  adaptive_icon_foreground: "assets/images/senta_icon.png"
  adaptive_icon_background: "#ffffff"
  android: true
  ios: true
  image_path: "assets/images/senta_icon.png"

# If ios Icon is too small, replace icon with 512 resolution icon instead of 1024
# FOR SETTING APP ICON RUN: flutter packages pub run flutter_launcher_icons:main

dev_dependencies:
  flutter_launcher_icons: ^0.7.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  image: 2.0.7

flutter:

  assets:
    - assets/images/senta_icon.png
    - assets/images/senta_icon_t.png

  uses-material-design: true

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
